### ISSUE TITLE
BiFrost

### ISSUE THREAD

**Issue by ytgui** [bosskwei/temp#20]

**Comment by ytgui** [comment]
![image](https://user-images.githubusercontent.com/12762888/50088453-1086ac00-023e-11e9-9bb3-f21de89af072.png)
![image](https://user-images.githubusercontent.com/12762888/50088660-960a5c00-023e-11e9-8858-4b21363a412b.png)
![image](https://user-images.githubusercontent.com/12762888/50088754-e1246f00-023e-11e9-8593-3ec8a93e3eab.png)
![image](https://user-images.githubusercontent.com/12762888/50088793-fef1d400-023e-11e9-9b23-01dc960159a5.png)
![image](https://user-images.githubusercontent.com/12762888/50088901-3e202500-023f-11e9-8001-d4d536ab3655.png)
![image](https://user-images.githubusercontent.com/12762888/50088926-4f693180-023f-11e9-8950-9e529a1b3c85.png)
![image](https://user-images.githubusercontent.com/12762888/50089098-d4ece180-023f-11e9-95fc-846c19c99647.png)

**Comment by bosskwei** [comment]
![image](https://user-images.githubusercontent.com/12762888/50088660-960a5c00-023e-11e9-8858-4b21363a412b.png)

**Comment by ytgui** [comment]
# Mali 架构与性能详述
## Synchronous API, Asynchronous Execution
1. The OpenGL ES API is specified as a synchronous API from the application perspective. (`glXXX()` -> `glDraw()`)
2. 由于 API （表面上）是同步的，draw call 后的所有 API 行为都被指定为要像渲染运算已经发生一样进行 (实际并非如此，甚至 glSwapBuffers 也不是同步的)
3. 驱动维持同步渲染的假象，只要 pipeline 装满，GPU 就会始终工作，不受 CPU 影响。

![image](https://user-images.githubusercontent.com/12762888/50819921-5844b300-1366-11e9-93df-3c130ef260e8.png)
![image](https://user-images.githubusercontent.com/12762888/50819965-76aaae80-1366-11e9-8f93-a4c2815742fb.png)
![image](https://user-images.githubusercontent.com/12762888/50819975-80ccad00-1366-11e9-85da-5a9c932cf521.png)

## Tail Rendering
```
foreach( primitive )
    foreach( fragment )
        render fragment
```
![image](https://user-images.githubusercontent.com/12762888/50821556-714f6300-136a-11e9-9d12-f5ed00cab425.png)

```
foreach( tile )
    foreach( primitive in tile )
        foreach( fragment in primitive in tile )
            render fragment
```
![image](https://user-images.githubusercontent.com/12762888/50821575-7d3b2500-136a-11e9-9229-e7a5af40db7a.png)

+ my understand
```Python
# Desktop GPU
for primitive in world:
    for vert in primitive:
        frag = rasterize(vert)
        framebuffer += blend(frag)
return framebuffer

# Mobile GPU
geometry_list = []
for primitive in tiles:
    for vert in primitive:
    vert = mvp_transform(vert)
    vert = face_culling(vert)
    geometry_list.append(vert)
for vert in geometry_list:
    frag = rasterize(vert)
    framebuffer += blend(frag)
return framebuffer
```

## Midgard Shader Core
![image](https://user-images.githubusercontent.com/12762888/51785211-35503680-218f-11e9-860e-2157cba49b18.png)
![image](https://user-images.githubusercontent.com/12762888/50089394-b2a79380-0240-11e9-8aa9-6cde24b229ff.png)
+ Graphics work for the GPU is queued in a pair of queues, one for vertex/tiling workloads and one for fragment workloads.
+ Vertex processing and fragment processing for different render targets can be running in parallel.
+ Single render target is broken into smaller pieces and distributed across all of the shader cores.
+ The shader cores in the system share a level 2 cache to improve performance, and to reduce memory bandwidth caused by repeated data fetches.

![image](https://user-images.githubusercontent.com/12762888/51785634-629fe300-2195-11e9-81ed-9a823678b630.png)
+ Structured as a number of fixed-function hardware blocks wrapped around a programmable "tripipe" execution core.
+ Tripipe design: one handling arithmetic operations, one handling memory load/store and varying access, and one handling texture access.
+ There is one load/store and one texture pipe per shader core, but the number of arithmetic pipelines can vary. (Mali-T880 has three but others have two)
+ Massively Multi-threaded Machine: 一个线程分发引擎，上百个硬件线程可以被分配到 tripipe 中
+ Arithmetic Pipeline: SIMD Vector Core, Mali-T760 with 16 cores is rated at 326 FP32 GFLOPS at 600MHz.
+ Texture Pipeline: The texture pipeline can return one bilinear filtered texel per clock
+ Load/Store Pipeline: Not related to texturing, For graphics workloads this means reading per-vertex attribute inputs and writing computed per-vertex outputs during vertex shading, and reading the per-vertex outputs values that were written by the vertex shader during fragment shading so they can be interpolated as a varying value. (load `highp vec4 varying` in a single cycle)

### Limits
+ Issue one vertex per shader core per clock.
+ Issue one fragment per shader core per clock.
+ Retire one pixel per shader core per clock.
+ Achieve 17 FP32 operations per A-pipe.
+ One vector load, one vector store, or one vector varying per LdSt-pipe.
+ 32-bits of DDR access (read and write) per core per clock.

### Performance (Mali-T760 MP8 @ 600MHz)
+ Fillrate: 8 pixels per clock = 4.8 GPix/s, 2314 frames per sec @ 1080P
+ Texture: 8 bilinear texels per clock = 4.8 GTex/s, 38 bilinear filtered texture lookups per pixel for 1080p @ 60 FPS
+ Arithmetic: 17 FP32 FLOPS per pipe per core = 163 FP32 GFLOPS, 1311 FLOPS per pixel for 1080p @ 60 FPS
+ Bandwidth: 256-bits of memory access per clock = 19.2GB/s read and write bandwidth

## Bifrost Shader Core
![image](https://user-images.githubusercontent.com/12762888/51785211-35503680-218f-11e9-860e-2157cba49b18.png)
+ The top-level architecture of a Bifrost GPU is the same as the earlier Midgard GPUs.
+ Unified shader core architecture.
+ Scale: Mali-G71 can scale from a single core to 32 cores.
+ Work Dispatch / Cache / Memory: Most same to Midgard.
+ Mali-G71 provides 64x 32-bit registers for the shader programs and hardware thread.
+ 

## Architecture
### Thread Dispatch
+ Each core contains a tri-pipe consisting of two arithmetic (A) pipelines, one load-store (LS) pipeline and one texturing (T) pipeline:
![image](https://user-images.githubusercontent.com/12762888/51810230-8f611100-22e1-11e9-9250-9bc2ede6fff2.png)
+ Thus, the peak throughput of each core is two A instruction words, one LS instruction word and one T instruction word per cycle.
### Optimize
+ Midgard architecture is not a single class:
   + Very Long Instruction Word (VLIW) architecture, such that each pipe contains multiple units and most instruction words contain instructions for multiple units.
   + Single Instruction Multiple Data (SIMD) architecture, such that most instructions operate on multiple data elements packed in 128-bit vector registers.
   + Fine-Grain Multi-Threaded (FGMT) architecture (细粒度多线程), such that each core runs its threads in a round-robin fashion (轮询调度), on every cycle switching to the next ready-to-execute thread. What's interesting, each thread has its individual program counter (unlike warp-based designs, where threads in a warp share the same program counter).

+ Tricks
   + The ratio of 2:1 of A-words to LS-words would be optimal.
   + Using vector operations in kernel code to allow for straightforward mapping to vector instructions by the compiler.
   + Having sufficient instruction level parallelism in kernel code to allow for dense packing of instructions into instruction words by the compiler. (改造算法使其对 VLIW 架构更友好，例如在代码中解除某些前后依赖关系)
   + Using a sufficient number of concurrently executing (or active) threads per core to hide the execution latency of instructions (which is the depth of a corresponding pipeline). (关键在于充分考虑寄存器的数量减少 thread 切换带来的开销)

### Geometry Performance
+ Index-Driven Vertex Shading (top: old, bottom: IDVS)
![image](https://user-images.githubusercontent.com/12762888/51817369-6fdbdf80-2305-11e9-8aad-f1dc9c3c663c.png)
![image](https://user-images.githubusercontent.com/12762888/51817370-723e3980-2305-11e9-9d49-111ede55a5b9.png)
+ The IDVS pipeline splits the vertex shader into two halves: one processing the position, and one processing the remaining varyings.
+ The index buffer is read first, and vertex shading is only submitted for small batches of vertices where at least one vertex in each batch is referenced by the index buffer. This allows vertex shading to jump spatial gaps in the index buffer.
+ Varying shading is only submitted for primitives with survive the clip-and-cull phase; this removes a significant amount of redundant computation and bandwidth for vertices contributing only to triangles which are culled.

## Ref
https://community.arm.com/graphics/b/blog/posts/the-mali-gpu-an-abstract-machine-part-1---frame-pipelining
https://community.arm.com/graphics/b/blog/posts/the-mali-gpu-an-abstract-machine-part-2---tile-based-rendering
https://community.arm.com/graphics/b/blog/posts/the-mali-gpu-an-abstract-machine-part-3---the-midgard-shader-core
https://community.arm.com/graphics/b/blog/posts/the-mali-gpu-an-abstract-machine-part-4---the-bifrost-shader-core
https://community.arm.com/graphics/b/blog/posts/arm-mali-compute-architecture-fundamentals

## TODO
（暂时无法理解的）
+ Eats, Shoots and Interleaves，提升几何变换性能，https://community.arm.com/graphics/b/blog/posts/eats-shoots-and-interleaves
