### ISSUE TITLE
Glow 2 - Framework

### ISSUE THREAD

**Issue by ytgui** [bosskwei/temp#31]
## Folder Structure
+ `glow`
  + `Base`: `IO, Image, Tensor, Train, Type ...`
  + `Backends`: `Backend, BackendUtils, CompiledFunction, LayoutConverter`
  + `CodeGen`: `MemoryAllocator`
  + `Converter`: `FunctionConverter, TypeAToTypeBFunctionConverter`
  + `ExecutionEngine`: `ExecutionEngine`
  + `Graph`: `Context, Graph, Node, Grad, Hook, NodeValue`
  + `IR`: `GraphScheduler, IR, IRGen, IRUtils, Instrs`
  + `Importer`: `ProtobufLoader, Caffe2ModelLoader, ONNXModelLoader, ONNXIFIModelLoader`
  + `Optimizer`: `GraphOptimizer, IROptimizer, Quantization, Lower`
  + `Quantization`: `Quantization, Serialization`
  + `Support`: `ThreadPool, Random`
  + `Testing`

**Comment by ytgui** [comment]
## BackendKind
> `include/glow/Backends/Backend.h`
```CPP
enum class BackendKind {
  Interpreter, // Execute the network with the built-in interpreter.
  OpenCL,      // Run the code on an OpenCL device.
  CPU,         // Compile and run the code on the host.
};
```

## Context
> `include/glow/Graph/Context.h`
1. This class provides a mapping between some graph nodes, which are a symbolic representation of some computation, and concrete tensors that represent the inputs and outputs to the graph.
2. The context owns the tensors and the graph uses these values as runtime. This is useful for the multi-threaded execution of code, where each thread has a different execution context.
3. The difference between this class and a regular map is that the Context owns the Tensors (not only the pointers) and manages their lifetime.

```CPP
class Context final {
private:
  // Maps placeholders to the tensors that back them.
  using PlaceholderMap = std::unordered_map<Placeholder *, Tensor *>;

  // Maps Placeholders to Tensors.
  PlaceholderMap map_;
}
```

## ExecutionEngine
> `include/glow/ExecutionEngine/ExecutionEngine.h`
1. ExecutionEngine owns the Graph, the backend, and the compiled function.
2. The Graph, etc in this class are defined as pointers, in order to erase the type and prevent the internal types from leaking out to the users of this class.

```CPP
class ExecutionEngine final {
private:
  // The Module that represents the high-level program.
  Module M_;

  // The network execution backend.
  std::unique_ptr<Backend> backend_;

  // A glow function compiled for this ExecutionEngine's backend.
  std::unique_ptr<CompiledFunction> function_;
}
```

## Module
> 1. `include/glow/Graph/Graph.h`
> 2. Represents the high-level program.
```CPP

class Module final {
  // Stores the functions in the module.
  FunctionList functions_;

  // A uniqued list of types. Types in this list can be equated by comparing their addresses.
  TypesList types_{};

  // Stores a list of unique variable names that were used by the module at some point.
  llvm::StringSet<> uniqueVariableNames_{};

  // A list of constants that the Module owns.
  ConstList constants_;

  // A list of placeholder nodes that the Module owns.
  PlaceholderList placeholders_;

  // Deterministic PRNG used to initialize weights in this module.
  PseudoRNG PRNG_;
};
```

## Backend
```CPP
// This is the interface that glow backends need to implement.
class Backend {
public:
virtual std::unique_ptr<CompiledFunction> compile(Function *F) const = 0;
virtual bool transformPreLowering(Function *F, CompilationMode mode) const { return false; }
virtual bool transformPostLowering(Function *F, CompilationMode mode) const { return false; }
virtual bool isOpSupported(Kinded::Kind opKind, ElemKind elementTy) const = 0;
virtual bool shouldLower(const Node *N) const { return true; }
virtual bool shouldShareBuffers() const { return true; }
}

// Backends that use Glow low-level IR should inherit from this class. It allows
// for unit tests to create low-level IR to compile and run.
class BackendUsingGlowIR : public Backend {
public:
  // Generate code for input IR function \param IR. \p ctx is the context that
  // maps the graph to the concrete execution environment for a specific
  // function. This is used only for unit testing.
  virtual std::unique_ptr<CompiledFunction>
  compileIR(std::unique_ptr<IRFunction> IR) const = 0;
};
```

**Comment by bosskwei** [comment]
## Placeholder
