### ISSUE TITLE
aws lambda

### ISSUE THREAD

**Issue by ytgui** [bosskwei/temp#99]
Function as a Service (FaaS)
https://www.zhihu.com/question/36947399
https://www.javaworld.com/article/3210726/serverless-computing-with-aws-lambda.html

**Comment by Aakashdeveloper** [comment]
Lambda function for 
DynamoDB
S3
Opensource Api
https://github.com/Aakashdeveloper/OCT_AWS_19/tree/master/Amazon-master

**Comment by ytgui** [comment]
@Aakashdeveloper thank you, really nice examples, how could you find my repo/notes :)
